    // --- 工具提示内容定义 (TOOLTIP DEFINITIONS FOR ICONS) ---
    const TOOLTIP_ICON_TARGETS = [
        { attachToSelector: 'label[for="main-prompt"]', tooltipKey: 'mainPrompt',
            zh: "主要提示词：描述你想要生成的图像内容、风格、构图等。例如：'a cat wearing a hat' (一只戴帽子的猫)。" },
        { attachToSelector: 'label[for="no-prompt"]', tooltipKey: 'noPrompt',
            zh: "排除词 (--no)：指定不希望出现在图像中的元素。例如输入 'trees' (树木)，最终指令会包含 '--no trees'。" },
        { attachToSelector: '.form-group.span-2#ar-section > label', tooltipKey: 'aspectRatio',
            zh: "图片尺寸 (--ar)：设置图像的宽高比。例如 16:9 (宽屏), 1:1 (方形), 2:3 (竖向)。不同模型版本支持的宽高比范围可能不同。" },
        { attachToSelector: 'label[for="stylize"]', tooltipKey: 'stylize',
            zh: "风格化 (--s)：影响Midjourney默认美学风格的应用强度。范围0-1000，默认100。值越高图像越具艺术性，但可能偏离提示词。" },
        { attachToSelector: 'label[for="chaos"]', tooltipKey: 'chaos',
            zh: "多样性 (--c)：控制生成结果的随机性和差异性。范围0-100，默认0。值越高，结果越出乎意料、更多样。" },
        { attachToSelector: 'label[for="weird"]', tooltipKey: 'weird',
            zh: "奇特化 (--w)：探索非主流、古怪的美学风格，使图像更奇特。范围0-3000，默认0。" },
        { attachToSelector: 'label[for="exp-slider"]', tooltipKey: 'experimental',
            zh: "探索性 (--exp)：用于启用或调整某些模型版本的实验性功能。范围0-100，默认0。具体效果依模型版本而定。" },
        { attachToSelector: 'label[for="version-dropdown-trigger"]', tooltipKey: 'version',
            zh: "版本 (--v, --niji)：选择Midjourney模型 (如v7, v6) 或Niji模型 (动漫风格)。不同版本有不同特性和风格。" },
        { attachToSelector: 'div[data-type="directImages"] .ref-module-header h4', tooltipKey: 'directImagesRef',
            zh: "图片提示 (Image Prompts)：直接在主要提示词区域粘贴图片URL。--iw 参数 (范围0-3, V6默认1) 调整图片提示相对于文本提示的权重。点击预览图可放大。" },
        { attachToSelector: 'div[data-type="cref"] .ref-module-header h4', tooltipKey: 'crefRef',
            zh: "角色参考 (--cref URL --cw N)：使用图片URL生成相似角色。--cw (0-100, 默认100) 调整参考强度。0仅关注面部，100关注面部、头发和衣服。点击预览图可放大。" },
        { attachToSelector: 'div[data-type="sref"] .ref-module-header h4', tooltipKey: 'srefRef',
            zh: "风格参考 (--sref URL --sw N)：使用图片URL迁移美学风格。--sw (0-1000, 默认100) 调整风格化强度。可使用 'random' 或数字风格码。点击预览图可放大。" },
        { attachToSelector: 'div[data-type="oref"] .ref-module-header h4', tooltipKey: 'orefRef',
            zh: "全方位参考 (--oref URL --ow N)：只支持一张图片，且仅能在 V7 版本中使用，允许同时使用图片和风格参考效果。--ow (0-100, 默认100) 调整整体参考强度。点击预览图可放大。" },
        { attachToSelector: '.form-group:has(.speed-btn-group) > label', tooltipKey: 'speedMode',
            zh: "速度 (--relax, --fast, --turbo)：选择生成模式。Relax模式不消耗Fast Credit，Turbo模式最快但消耗更多。Fast为默认速度。" },
        { attachToSelector: '.form-group:has(.mode-btn-group) > label', tooltipKey: 'renderMode',
            zh: "模式 (--raw)：标准模式或原始模式。原始模式 (--raw) 会减少Midjourney的默认风格应用，更贴近提示词。V6以上版本效果更明显。" },
        { attachToSelector: '.form-group:has(.visibility-btn-group) > label', tooltipKey: 'visibilityMode',
            zh: "可见性 (--public, --stealth)：控制图像是否公开。默认公开。隐身模式 (--stealth) 仅限Pro Plan订阅者。" },
        { attachToSelector: 'label[for="seed-input"]', tooltipKey: 'seed',
            zh: "种子 (--seed)：指定一个数字 (0-4294967295) 以生成视觉上更一致的图像。留空则随机。" },
        { attachToSelector: 'label[for="quality-slider"]', tooltipKey: 'quality',
            zh: "质量 (--q)：调整渲染所花费的时间和细节。脚本内可选值: 0.25, 0.5, 1, 2, 4。默认1。不同模型实际支持的值可能不同，请参考官方文档。" },
        { attachToSelector: 'label[for="stop-slider"]', tooltipKey: 'stop',
            zh: "停止 (--stop)：在图像生成过程中提前停止 (10-100)。值越小，图像越模糊、细节越少。默认100 (不停止)。" },
        { attachToSelector: 'label[for="r-slider"]', tooltipKey: 'repeat',
            zh: "批量任务 (--r)：重复运行作业多次，以便快速生成多个变体。通常为2-10次。在Relax模式下不可用，需开启fast模式。" },
        { attachToSelector: 'label[for="personal-params"]', tooltipKey: 'personalParams',
            zh: "个性化 (--p)：应用您之前保存的个性化代码，以便快速应用一组常用的参数或风格影响。需提前在Midjourney网站设置。" },
        { attachToSelector: 'label[for="tile-toggle-switch"]', tooltipKey: 'tile',
            zh: "重复图案 (--tile)：生成可作为无缝重复纹理或图案的图像。" },
        { attachToSelector: 'label[for="draft-toggle-switch"]', tooltipKey: 'draft',
            zh: "草稿模式 (--draft)：生成图像速度更快且成本更低，但细节较少，适合快速迭代想法。" }
    ];
